<LoginScreen>:
    MDFloatLayout:
        md_bg_color: utils.get_color_from_hex("#ffffff")
        MDBoxLayout:
            orientation: "vertical"
            padding: dp(20)
            Widget:
                size_hint: 1, None
                height: dp(50)
            Image:
                source: "images/lock_icon.png"
                size_hint: 1, None
                height: dp(100)
#                size_hint: 0.5, 0.2
#                pos_hint: {"center_x": 0.5}
            MDLabel:
                text: "[size=38][b]Connexion[/b][/size]"
                markup: True
                halign: "center"
            MDLabel:
                text: "[size=20]Plateforme pour CP[/size]"
                markup: True
                halign: "center"
            MDTextField:
                mode: "outlined"
                on_text: root.saisie_username(self.text)
                MDTextFieldHintText:
                    text: "Nom d'utilisateur"
                MDTextFieldLeadingIcon:
                    icon: "account-box-outline"
            Widget:
                size_hint: 1, None
                height: dp(20)
            MDTextField:
                mode: "outlined"
                on_text: root.saisie_mot_passe(self.text)
                MDTextFieldHintText:
                    text: "Mot de passe"
                MDTextFieldLeadingIcon:
                    icon: "lock"

            Widget:
                size_hint: 1, None
                height: dp(20)

            MDButton:
                theme_width: "Custom"
                size_hint: 1, 1
                on_release: root.valider()
                MDButtonText:
                    text: "Confirmer"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}


            Widget:
