<LoginScreen>:
    MDFloatLayout:
        md_bg_color: utils.get_color_from_hex("#ffffff")
        MDBoxLayout:
            orientation: "vertical"
            padding: dp(20)
            Widget:
                size_hint: 1, None
                height: dp(50)
            Image:
                source: "images/lock_icon.png"
                size_hint: 1, None
                height: dp(100)
#                size_hint: 0.5, 0.2
#                pos_hint: {"center_x": 0.5}


            Widget:
